const movies = [
  {
    id: 1,
    title: 'It Ends with Us',
    category: 'drama',
    rate: 6.4,
    img: 'https://wegotthiscovered.com/wp-content/uploads/2023/07/Blake-Lively-It-Ends-With-Us.png',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 2,
    title: 'The Conjuring 2',
    category: 'horror',
    rate: 7.3,
    img: 'https://tse1.mm.bing.net/th/id/OIP.64A-vl6jOblEl3GWxP1s_QHaEK?pid=Api&P=0&h=220',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 3,
    title: 'Carry-On',
    category: 'action',
    rate: 6.5,
    img: 'https://tse4.mm.bing.net/th/id/OIP.Ywd2xV_jr_DPgCajRH4vbwHaDt?pid=Api&P=0&h=220',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 4,
    title: 'Norbit',
    category: 'comedy',
    rate: 4.2,
    img: 'https://eurweb.com/wp-content/uploads/2024/11/Eddie-Murphy-Norbit-poster.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 5,
    title: 'Wicked',
    category: 'fantasy',
    rate: 7.5,
    img: 'https://www.seeingdandy.com/wp-content/uploads/2024/11/wicked-movie-poster-735x490.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 6,
    title: 'Until Dawn',
    category: 'horror',
    rate: 5.8,
    img: 'https://images.squarespace-cdn.com/content/v1/51b3dc8ee4b051b96ceb10de/ff0e9430-6d23-4233-bb72-29c866ca9aa8/until-dawn-character-posters-spotlight-monsters-in-the-movie-new-trailer-drops-tomorrow.jpg?format=2500w',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 7,
    title: 'Anabelle Comes Home',
    category: 'horror',
    rate: 5.9,
    img: 'https://tse3.mm.bing.net/th/id/OIP.lhgZ8Wf8yoWCt046EpSKAwHaEo?pid=Api&P=0&h=220',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 8,
    title: 'M3GAN 2.0',
    category: 'action',
    rate: 6.7,
    img: 'https://tse3.mm.bing.net/th/id/OIP.AyDCJLkq2VeubiKqmH_6XQHaEK?pid=Api&P=0&h=220',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
  {
    id: 9,
    title: 'The Little Mermaid',
    category: 'fantasy',
    rate: 7.2,
    img: 'https://tse3.mm.bing.net/th/id/OIP.0SP4LHSRfcENxsYvEQrqawHaEK?pid=Api&P=0&h=220',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },

  {
    id: 10,
    title: 'Last Breath',
    category: 'drama',
    rate: 6.6,
    img: 'https://www.filmofilia.com/wp-content/uploads/2025/02/Last-Breath-860x475.jpg',
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita ipsa qui fugiat at cupiditate, corporis illo quae reprehenderit doloremque veritatis architecto hic.`,
  },
];
export default movies;
